"""add_metadata_overrides_to_document

Revision ID: 2b87e5523cfb
Revises: a978a8428f3d
Create Date: 2025-05-08 23:37:14.161694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b87e5523cfb'
down_revision = 'a978a8428f3d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 