"""Add ExtractedData model

Revision ID: 4a314f2bf582
Revises: 911bcbd45b87
Create Date: 2025-05-04 01:17:15.301537

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4a314f2bf582'
down_revision = '911bcbd45b87'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extracted_data',
    sa.Column('extracted_data_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('extraction_timestamp', sa.DateTime(), nullable=False),
    sa.Column('review_status', sa.Enum('PENDING_REVIEW', 'REVIEWED_CORRECTED', 'REVIEWED_APPROVED', name='reviewstatus'), nullable=False),
    sa.Column('reviewed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('review_timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('extracted_data_id')
    )
    op.create_index(op.f('ix_extracted_data_document_id'), 'extracted_data', ['document_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_extracted_data_document_id'), table_name='extracted_data')
    op.drop_table('extracted_data')
    # ### end Alembic commands ### 